// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6SlKtQWj_RHcw4qpZ0rLPrrSGsfkIxeM',
    appId: '1:722764029231:web:09fe515ea954649d5555da',
    messagingSenderId: '722764029231',
    projectId: 'sarisync-337e3',
    authDomain: 'sarisync-337e3.firebaseapp.com',
    storageBucket: 'sarisync-337e3.firebasestorage.app',
    measurementId: 'G-RPXDM59KNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-fpDsKwcq_ElqYqhSjBL66vM5hv4i1mg',
    appId: '1:722764029231:android:9cae33016d29e1df5555da',
    messagingSenderId: '722764029231',
    projectId: 'sarisync-337e3',
    storageBucket: 'sarisync-337e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz2czcski7_vkp40-vXJE8rgowFge_qtU',
    appId: '1:722764029231:ios:2325217be1cfbf135555da',
    messagingSenderId: '722764029231',
    projectId: 'sarisync-337e3',
    storageBucket: 'sarisync-337e3.firebasestorage.app',
    iosBundleId: 'com.example.sarisync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz2czcski7_vkp40-vXJE8rgowFge_qtU',
    appId: '1:722764029231:ios:2325217be1cfbf135555da',
    messagingSenderId: '722764029231',
    projectId: 'sarisync-337e3',
    storageBucket: 'sarisync-337e3.firebasestorage.app',
    iosBundleId: 'com.example.sarisync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6SlKtQWj_RHcw4qpZ0rLPrrSGsfkIxeM',
    appId: '1:722764029231:web:dfffce0b7488b03c5555da',
    messagingSenderId: '722764029231',
    projectId: 'sarisync-337e3',
    authDomain: 'sarisync-337e3.firebaseapp.com',
    storageBucket: 'sarisync-337e3.firebasestorage.app',
    measurementId: 'G-C9YHQ9W166',
  );
}
